default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: bookinghub_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: bookinghub_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
